### ISSUE TITLE
Login to api fails

### ISSUE THREAD

**Issue by Seji64** [Wilhelmsson177/tonie-api#107]
**Describe the bug**
A login to the tonie api no longer works. Therefore it worked so they probably changed something.

**To Reproduce**

Do a simple login:  `tonie_api = TonieAPI(args.tonie_username, args.tonie_password)`

**Additional context**
Stack Trace:

```
Traceback (most recent call last):
  File "/app/spoonie.py", line 402, in main
    tonie_api = TonieAPI(args.tonie_username, args.tonie_password)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tonie_api/api.py", line 35, in __init__
    self.session.acquire_token(username=username, password=password)
  File "/usr/local/lib/python3.12/site-packages/tonie_api/session.py", line 23, in acquire_token
    self.token = self._acquire_token(username, password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tonie_api/session.py", line 33, in _acquire_token
    response = requests.post(self.OPENID_CONNECT, data=data, timeout=15)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
```

**Comment by Seji64** [comment]
Getting the token via Postman surprisingly  works 😵‍💫

**Comment by heilmic** [comment]
Can confirm, i get the same error.

**Comment by Seji64** [comment]
@heilmoa i did a fork and "patched" it, take a look if you want: https://github.com/Seji64/tonie-api
